a=float(input("Enter Value of a:"))
b=float(input("Enter Value of b:"))
print("-"*50)
print("\t\t {} + {} = {}".format(a,b,a+b))
print("\t\t {} - {} = {}".format(a,b,a-b))
print("\t\t {} * {} = {}".format(a,b,a*b))
print("\t\t {} / {} = {}".format(a,b,a/b))
print("\t\t {} // {} = {}".format(a,b,a//b))
print("\t\t {} % {} = {}".format(a,b,a%b))
print("\t\t {} ** {} = {}".format(a,b,a**b))
print("-"*50)