#Program for Demonstrating the need of Relational Operators
a=float(input("Enter Number of a: "))
b=float(input("Enter Number of b: "))
print("*"*90)
print("\tResult of Relational Expression")
print("*"*90)
print("\t\t{} > {} = {}".format(a,b,a>b))
print("\t\t{} < {} = {}".format(a,b,a<b))
print("\t\t{} == {} = {}".format(a,b,a==b))
print("\t\t{} != {} = {}".format(a,b,a!=b))
print("\t\t{} >= {} = {}".format(a,b,a>=b))
print("\t\t{} <= {} = {}".format(a,b,a<=b))
print("*"*90)
print("*"*90)